version: "3.8"

services:
  drug_shop:
    container_name: drug_shop
    restart: always
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile
    command: run
    volumes:
      - ./backend/static:/app/backend/static
      - ./backend/media:/app/backend/media
    env_file:
      .env
    ports:
      - 127.0.0.1:8000:8000
    links:
      - db
    depends_on:
      - db


  db:
    container_name: drub_shop_db
    restart: always
    image: postgres:14-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    env_file:
      .env
    ports:
      - '5435:5432'

volumes:
  postgres-data: